import type { JSONContent } from "@tiptap/react";
import { notFound } from "next/navigation";
import { changeEditorialStatus, saveNewsCover, saveNewsRelatedProducts, updateEditorialContent } from "@/app/admin/actions";
import { RichTextEditor } from "@/components/admin/rich-text-editor";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Field, FieldDescription, FieldGroup, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { requireSecureAdmin } from "@/lib/admin-session";
import { db } from "@/lib/db";

export const metadata = { title: "编辑方案或文章", robots: { index: false, follow: false } };
type Props = { params: Promise<{ type: string; id: string }>; searchParams: Promise<{ saved?: string; error?: string }> };
type TranslationRecord = { locale: "zh" | "en" | "ru"; slug: string; title: string; summary: string; body: unknown; seoTitle: string; seoDescription: string; imageAlt?: string };

export default async function Page({ params, searchParams }: Props) {
  const [{ type, id }, query, session] = await Promise.all([params, searchParams, requireSecureAdmin()]);
  if (!["solutions", "industries", "cases", "news"].includes(type)) notFound();
  let item: { id: string; status: string; authorName?: string; category?: "INDUSTRY_INSIGHTS" | "BUYING_GUIDE" | "TUTORIAL_GUIDE"; coverImageId?: string | null; translations: TranslationRecord[]; relatedProducts?: Array<{ productId: string; sortOrder: number }> } | null;
  if (type === "solutions") item = await db.solution.findUnique({ where: { id }, include: { translations: true } });
  else if (type === "industries") item = await db.industry.findUnique({ where: { id }, include: { translations: true } });
  else if (type === "cases") item = await db.caseStudy.findUnique({ where: { id }, include: { translations: true } });
  else item = await db.newsArticle.findUnique({ where: { id }, include: { translations: true, relatedProducts: { orderBy: { sortOrder: "asc" } } } });
  if (!item) notFound();
  const eligibleAssets = type === "news" ? await db.mediaAsset.findMany({ where: { kind: "IMAGE", scanStatus: "CLEAN", rightsApproved: true }, select: { id: true, originalName: true, width: true, height: true }, orderBy: { createdAt: "desc" }, take: 100 }) : [];
  const selectableProducts = type === "news" ? await db.product.findMany({ where: { status: "PUBLISHED", brand: { archivedAt: null, rightsConfirmed: true }, category: { status: "PUBLISHED" }, translations: { some: { locale: "zh", published: true } } }, include: { brand: true, translations: { where: { locale: "zh", published: true } } }, orderBy: [{ brand: { name: "asc" } }, { model: "asc" }] }) : [];
  return <main className="flex flex-col gap-6 p-5 md:p-8">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-3"><h1 className="text-2xl font-semibold">编辑方案或文章</h1><Badge variant="secondary">{item.status}</Badge></div><p className="mt-2 text-sm text-muted-foreground">保存修订后回到草稿；发布和归档仅限管理员。</p></div><Button variant="outline" render={<a href="/admin/editorial" />}>返回列表</Button></div>
    {query.saved ? <Alert><AlertTitle>{query.saved === "cover" ? "新闻封面已保存" : query.saved === "related-products" ? "相关产品已保存" : "修订已保存"}</AlertTitle><AlertDescription>内容已保存为草稿，发布后将在公开站显示。</AlertDescription></Alert> : null}
    {query.error ? <Alert variant="destructive"><AlertTitle>无法完成操作</AlertTitle><AlertDescription>{query.error === "empty-body" ? "中英俄三语正文都必须包含文字内容。" : query.error === "cover-not-eligible" ? "封面必须是已通过扫描并确认授权的图片。" : query.error === "duplicate-related-product" ? "同一个产品不能占用多个推荐位置。" : query.error === "invalid-related-product" ? "只能选择当前可公开展示的产品。" : query.error}</AlertDescription></Alert> : null}
    {session.user.role === "ADMIN" ? <div className="flex flex-wrap gap-3"><form action={changeEditorialStatus}><input type="hidden" name="type" value={type} /><input type="hidden" name="id" value={id} /><Button type="submit" name="status" value="PUBLISHED" disabled={item.status === "PUBLISHED"}>发布</Button></form><form action={changeEditorialStatus}><input type="hidden" name="type" value={type} /><input type="hidden" name="id" value={id} /><Button type="submit" name="status" value={item.status === "ARCHIVED" ? "DRAFT" : "ARCHIVED"} variant="outline">{item.status === "ARCHIVED" ? "恢复为草稿" : "归档"}</Button></form></div> : null}
    {type === "news" ? <Card className="max-w-5xl"><CardHeader><CardTitle>新闻封面图</CardTitle><CardDescription>从媒体库选择已通过扫描并确认授权的图片；不选择则不显示封面。</CardDescription></CardHeader><CardContent><form action={saveNewsCover} className="flex flex-col gap-5"><input type="hidden" name="articleId" value={id} /><Field><FieldLabel htmlFor="coverImageId">封面素材</FieldLabel><select id="coverImageId" name="coverImageId" defaultValue={item.coverImageId ?? ""} className="h-10 rounded-lg border bg-background px-3"><option value="">不使用封面</option>{eligibleAssets.map((asset) => <option key={asset.id} value={asset.id}>{asset.originalName} · {asset.width ?? "?"}×{asset.height ?? "?"}</option>)}</select><FieldDescription>素材可在媒体库上传和复核。</FieldDescription></Field><div className="grid gap-5 sm:grid-cols-3">{(["zh", "en", "ru"] as const).map((locale) => <Field key={locale}><FieldLabel htmlFor={`${locale}ImageAlt`}>{locale.toUpperCase()} 图片 Alt</FieldLabel><Input id={`${locale}ImageAlt`} name={`${locale}ImageAlt`} defaultValue={item.translations.find((entry) => entry.locale === locale)?.imageAlt ?? ""} placeholder="留空则使用新闻标题" maxLength={200} /></Field>)}</div><Button type="submit" className="self-start">保存封面设置</Button></form></CardContent></Card> : null}
    {type === "news" ? <Card className="max-w-5xl"><CardHeader><CardTitle>相关产品</CardTitle><CardDescription>最多指定 4 个产品，推荐位置决定前台顺序；留空的位置将根据新闻关键词、产品分类和品牌自动补足。</CardDescription></CardHeader><CardContent><form action={saveNewsRelatedProducts} className="flex flex-col gap-5"><input type="hidden" name="articleId" value={id} /><div className="grid gap-5 sm:grid-cols-2">{[0, 1, 2, 3].map((index) => <Field key={index}><FieldLabel htmlFor={`relatedProduct${index + 1}Id`}>推荐位置 {index + 1}</FieldLabel><select id={`relatedProduct${index + 1}Id`} name={`relatedProduct${index + 1}Id`} defaultValue={item.relatedProducts?.find((entry) => entry.sortOrder === index)?.productId ?? ""} className="h-10 w-full rounded-lg border bg-background px-3"><option value="">自动推荐补足</option>{selectableProducts.map((product) => <option key={product.id} value={product.id}>{product.brand.name} · {product.model} · {product.translations[0]?.name ?? "缺少中文名称"}</option>)}</select></Field>)}</div><FieldDescription>不能重复选择同一个产品。若产品下架或不再符合公开条件，前台会自动寻找其他产品补足。</FieldDescription><Button type="submit" className="self-start">保存相关产品</Button></form></CardContent></Card> : null}
    <Card className="max-w-5xl"><CardHeader><CardTitle>三语内容</CardTitle><CardDescription>标题、摘要、正文及 SEO 字段都必须来自可核验资料。</CardDescription></CardHeader><CardContent><form action={updateEditorialContent}><input type="hidden" name="type" value={type} /><input type="hidden" name="id" value={id} /><FieldGroup>{type === "news" ? <><Field><FieldLabel htmlFor="authorName">新闻作者</FieldLabel><Input id="authorName" name="authorName" defaultValue={item.authorName} required /><FieldDescription>请使用可核验的作者或编辑团队名称。</FieldDescription></Field><Field><FieldLabel htmlFor="newsCategory">新闻分类</FieldLabel><select id="newsCategory" name="newsCategory" defaultValue={item.category ?? "INDUSTRY_INSIGHTS"} className="h-10 w-full rounded-lg border bg-background px-3"><option value="INDUSTRY_INSIGHTS">行业洞察</option><option value="BUYING_GUIDE">选购指南</option><option value="TUTORIAL_GUIDE">教程指南</option></select><FieldDescription>前台新闻动态页会按此分类切换显示。</FieldDescription></Field></> : null}{(["zh", "en", "ru"] as const).map((locale) => { const translation = item.translations.find((entry) => entry.locale === locale); if (!translation) return <Alert variant="destructive" key={locale}><AlertTitle>缺少 {locale.toUpperCase()} 内容</AlertTitle><AlertDescription>该记录数据不完整，暂不能通过此页面修订。</AlertDescription></Alert>; return <section className="flex flex-col gap-5 border-t pt-6" key={locale}><h2 className="text-lg font-semibold">{locale.toUpperCase()}</h2><div className="grid gap-5 sm:grid-cols-2"><Field><FieldLabel htmlFor={`${locale}Title`}>标题</FieldLabel><Input id={`${locale}Title`} name={`${locale}Title`} defaultValue={translation.title} required /></Field><Field><FieldLabel htmlFor={`${locale}Slug`}>Slug</FieldLabel><Input id={`${locale}Slug`} name={`${locale}Slug`} defaultValue={translation.slug} pattern="[a-z0-9][a-z0-9-]*" required /></Field></div><Field><FieldLabel htmlFor={`${locale}Summary`}>摘要</FieldLabel><Textarea id={`${locale}Summary`} name={`${locale}Summary`} defaultValue={translation.summary} required minLength={20} /></Field><div className="grid gap-5 sm:grid-cols-2"><Field><FieldLabel htmlFor={`${locale}SeoTitle`}>SEO 标题</FieldLabel><Input id={`${locale}SeoTitle`} name={`${locale}SeoTitle`} defaultValue={translation.seoTitle} required maxLength={120} /></Field><Field><FieldLabel htmlFor={`${locale}SeoDescription`}>Meta Description</FieldLabel><Textarea id={`${locale}SeoDescription`} name={`${locale}SeoDescription`} defaultValue={translation.seoDescription} required maxLength={180} /></Field></div><RichTextEditor name={`${locale}Body`} label="正文" initialContent={translation.body as JSONContent} /></section>; })}<Button type="submit" className="self-start">保存三语修订</Button></FieldGroup></form></CardContent></Card>
  </main>;
}
