import type { Metadata } from "next";
import { SearchIcon } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Empty, EmptyDescription, EmptyHeader, EmptyTitle } from "@/components/ui/empty";
import { Field, FieldGroup, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Link } from "@/i18n/navigation";
import { getEditorial, getProducts } from "@/lib/content-repository";
import { assertLocale } from "@/lib/locale";
import { localizedMetadata } from "@/lib/seo";
type Props = { params: Promise<{ locale: string }>; searchParams: Promise<{ q?: string }> };
const copy = { zh: ["站内搜索", "搜索产品、型号、方案、案例和新闻。", "搜索", "未找到结果"], en: ["Site search", "Search products, models, solutions, cases, and news.", "Search", "No results found"], ru: ["Поиск по сайту", "Поиск продукции, моделей, решений, проектов и новостей.", "Поиск", "Ничего не найдено"] } as const;
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { locale } = await params; assertLocale(locale); return localizedMetadata(locale, "/search", copy[locale][0], copy[locale][1], true); }
export default async function Page({ params, searchParams }: Props) { const { locale } = await params; assertLocale(locale); const { q = "" } = await searchParams; const needle = q.trim().toLowerCase(); const [products, solutions, cases, news] = await Promise.all([getProducts(locale), getEditorial(locale, "industries"), getEditorial(locale, "cases"), getEditorial(locale, "news")]); const results = needle ? [...products.map((item) => ({ id: item.id, title: item.name, summary: item.shortDescription, href: `/products/${item.slug}`, text: `${item.name} ${item.model} ${item.brand} ${item.categoryName} ${item.shortDescription} ${item.attributes.map((a) => `${a.label} ${a.value}`).join(" ")}` })), ...solutions.map((item) => ({ ...item, href: `/solutions/${item.slug}`, text: `${item.title} ${item.summary}` })), ...cases.map((item) => ({ ...item, href: `/cases/${item.slug}`, text: `${item.title} ${item.summary}` })), ...news.map((item) => ({ ...item, href: `/news/${item.slug}`, text: `${item.title} ${item.summary}` }))].filter((item) => item.text.toLowerCase().includes(needle)) : []; return <main id="main-content" className="page-shell section-pad"><div className="mx-auto flex max-w-4xl flex-col gap-10"><div className="flex flex-col gap-5"><h1 className="section-title heading-underlined heading-underlined-left">{copy[locale][0]}</h1><p className="text-lg text-muted-foreground">{copy[locale][1]}</p></div><form><FieldGroup><Field><FieldLabel htmlFor="site-search">{copy[locale][2]}</FieldLabel><div className="flex gap-2"><Input id="site-search" name="q" defaultValue={q} /><Button type="submit"><SearchIcon data-icon="inline-start" />{copy[locale][2]}</Button></div></Field></FieldGroup></form>{needle && !results.length ? <Empty className="border"><EmptyHeader><EmptyTitle>{copy[locale][3]}</EmptyTitle><EmptyDescription>{q}</EmptyDescription></EmptyHeader></Empty> : <div className="flex flex-col divide-y border-y">{results.map((item) => <Link href={item.href} key={item.id} className="flex flex-col gap-2 py-6"><h2 className="text-xl font-medium">{item.title}</h2><p className="line-clamp-2 text-sm leading-6 text-muted-foreground">{item.summary}</p></Link>)}</div>}</div></main>; }
