import { BarChart3Icon, BoxesIcon, FileClockIcon, FileImageIcon, FileTextIcon, FolderTreeIcon, InboxIcon, LayoutDashboardIcon, MessageCircleIcon, SettingsIcon, TagsIcon } from "lucide-react";
import { AdminBrandMark as BrandMark } from "@/components/brand-mark";
import { Sidebar, SidebarContent, SidebarFooter, SidebarGroup, SidebarGroupContent, SidebarGroupLabel, SidebarHeader, SidebarInset, SidebarMenu, SidebarMenuButton, SidebarMenuItem, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import type { Role } from "@/types/domain";

const items = [{ href: "/admin", label: "概览", icon: LayoutDashboardIcon }, { href: "/admin/analytics", label: "统计分析", icon: BarChart3Icon }, { href: "/admin/products", label: "产品", icon: BoxesIcon }, { href: "/admin/categories", label: "产品分类", icon: FolderTreeIcon }, { href: "/admin/media", label: "媒体库", icon: FileImageIcon }, { href: "/admin/taxonomy", label: "品牌与参数", icon: TagsIcon }, { href: "/admin/editorial", label: "方案与文章", icon: FileTextIcon }, { href: "/admin/inquiries", label: "询价", icon: InboxIcon }, { href: "/admin/customer-service", label: "在线客服", icon: MessageCircleIcon }, { href: "/admin/imports", label: "资料与采集", icon: FileTextIcon }, { href: "/admin/jobs", label: "任务", icon: FileClockIcon }, { href: "/admin/settings", label: "设置", icon: SettingsIcon }];
export function AdminShell({ children, user }: { children: React.ReactNode; user: { name: string; email: string; role: Role } }) {
  return <SidebarProvider><Sidebar collapsible="offcanvas"><SidebarHeader><div className="px-2 py-3"><BrandMark /></div></SidebarHeader><SidebarContent><SidebarGroup><SidebarGroupLabel>内容管理</SidebarGroupLabel><SidebarGroupContent><SidebarMenu>{items.map((item) => <SidebarMenuItem key={item.href}><SidebarMenuButton render={<a href={item.href} />} tooltip={item.label}><item.icon /><span>{item.label}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroupContent></SidebarGroup></SidebarContent><SidebarFooter><div className="flex flex-col gap-1 px-2 py-3 text-xs"><strong>{user.name}</strong><span className="truncate text-sidebar-foreground/70">{user.email}</span><span>{user.role}</span></div></SidebarFooter></Sidebar><SidebarInset className="min-w-0 max-w-full overflow-x-hidden"><header className="flex h-14 items-center gap-3 border-b px-4"><SidebarTrigger /><span className="text-sm font-medium">HEFENGQI 内容后台</span></header>{children}</SidebarInset></SidebarProvider>;
}
