import type { Locale } from "@/types/domain";

const zh = {
  title: "技术支持与故障排查",
  description: "从设备型号出发，查找产品资料与技术指南，让现场问题有据可循。",
  home: "首页", support: "技术支持", search: "搜索", searching: "正在查找…",
  searchLabel: "查找设备与技术资料", searchPlaceholder: "输入型号、设备名称或问题关键词",
  searchHint: "支持型号中的空格、连字符等不同写法。",
  brand: "品牌", allBrands: "全部品牌", type: "设备类型", allTypes: "全部类型", filters: "筛选条件", clear: "清除筛选",
  devices: "按设备查找支持", devicesDescription: "选择设备，查看型号资料并提交具体的技术问题。",
  deviceCount: "个设备", device: "设备型号", resources: "可用资料", open: "查看支持",
  productData: "产品资料", technicalArticles: "技术文章", previous: "上一页", next: "下一页", pagination: "设备列表分页",
  noResults: "没有找到匹配的设备", noResultsDescription: "试试更短的型号或清除筛选，也可以直接向我们提供设备铭牌与问题描述。",
  articlesTitle: "技术指南与参考", articlesDescription: "从已有技术文章中了解设备选型、接口与日常维护。", allArticles: "查看全部文章",
  contactTitle: "有设备型号，也有现场问题？", contactDescription: "提供准确型号、告警原文和现场现象，便于核对资料与适配条件。", contact: "提交技术咨询",
  detailSuffix: "设备资料与技术支持", contents: "本页目录", overview: "设备信息", alarms: "告警与排查资料", prepare: "提交现场信息", related: "相关技术文章",
  model: "设备型号", category: "设备类型", version: "控制器 / 软件版本", versionPlaceholder: "如能从现有界面查看，请填写版本",
  versionUnknown: "需根据现场设备确认", productLink: "查看完整产品参数", source: "资料入口", sourceDescription: "以下为当前产品目录资料。现场设备的控制器、软件版本和配置仍需另行核对。",
  alarmCode: "告警代码 / 名称", led: "指示灯状态", cause: "可能原因", procedure: "排查方法",
  noAlarms: "该型号暂未收录公开的告警排查手册", noAlarmsDescription: "请提供告警原文与控制器版本，以便确认适用资料。不同版本的告警定义和处理方式可能不同。",
  prepareDescription: "记录现有界面可见的信息即可。电气测量、拆机与更换操作应按对应原厂手册由合格人员执行。",
  alarmLabel: "告警原文或现场现象", alarmPlaceholder: "例如：屏幕显示的完整告警文字、出现时间、受影响的设备",
  contextHelp: "这些信息将随型号一起带入咨询表单，你可以在提交前补充。",
  notes: [
    { title: "确认准确型号", body: "记录设备铭牌、系统型号，以及控制器或模块型号。" },
    { title: "保留告警信息", body: "记录完整告警文字、指示灯颜色、出现时间及是否持续。" },
    { title: "说明现场变化", body: "说明近期是否更换设备、升级软件或调整配置。" },
  ],
  noArticles: "暂无关联的技术文章", noArticlesDescription: "可以浏览技术指南，或就该型号提交具体问题。",
  partsTitle: "需要更换模块或配套设备？", partsDescription: "请先确认完整型号、系统配置与兼容条件，再咨询适配产品。", partsAction: "咨询适配产品",
  inquirySubject: "技术支持咨询", inquiryPage: "资料页面",
};

type SupportCopy = { [K in keyof typeof zh]: K extends "notes" ? Array<{ title: string; body: string }> : string };

const en: SupportCopy = {
  title: "Support & Troubleshooting",
  description: "Find equipment information and technical guides by model, and bring clarity to on-site issues.",
  home: "Home", support: "Support", search: "Search", searching: "Searching…",
  searchLabel: "Find equipment and technical information", searchPlaceholder: "Search a model, device or topic",
  searchHint: "Model searches also match variations in spacing and hyphens.",
  brand: "Brand", allBrands: "All brands", type: "Equipment type", allTypes: "All types", filters: "Filters", clear: "Clear filters",
  devices: "Find support by equipment", devicesDescription: "Choose a device to view its information and ask a specific technical question.",
  deviceCount: "devices", device: "Equipment model", resources: "Available resources", open: "View support",
  productData: "Product information", technicalArticles: "Technical articles", previous: "Previous", next: "Next", pagination: "Equipment pages",
  noResults: "No matching equipment", noResultsDescription: "Try a shorter model name or clear the filters. You can also send us the nameplate details and a description of the issue.",
  articlesTitle: "Technical guides & references", articlesDescription: "Explore published articles on equipment selection, interfaces and maintenance.", allArticles: "View all articles",
  contactTitle: "Have a model and an on-site issue?", contactDescription: "Share the exact model, alarm text and observed symptoms to help identify relevant information and compatibility requirements.", contact: "Request technical support",
  detailSuffix: "Equipment information & support", contents: "On this page", overview: "Equipment information", alarms: "Alarms & troubleshooting", prepare: "Share on-site information", related: "Related technical articles",
  model: "Equipment model", category: "Equipment type", version: "Controller / software version", versionPlaceholder: "Enter the version if visible in the existing interface",
  versionUnknown: "Confirm against the installed equipment", productLink: "View full product specifications", source: "Product reference", sourceDescription: "Information below comes from the current product catalogue. Confirm the controller, software version and configuration of the installed equipment separately.",
  alarmCode: "Alarm code / name", led: "LED status", cause: "Possible cause", procedure: "Troubleshooting",
  noAlarms: "No public alarm guide is available for this model yet", noAlarmsDescription: "Share the original alarm text and controller version to help identify applicable documentation. Alarm definitions and procedures may vary by version.",
  prepareDescription: "Record information visible in the existing interface. Electrical measurements, disassembly and replacement should follow the applicable manufacturer's manual and be performed by qualified personnel.",
  alarmLabel: "Alarm text or observed symptoms", alarmPlaceholder: "Include the complete alarm text, when it appeared and which equipment is affected",
  contextHelp: "Your model and these details will be added to the enquiry form for you to review before sending.",
  notes: [
    { title: "Identify the exact model", body: "Record the nameplate, system model and controller or module model." },
    { title: "Keep the alarm details", body: "Record the full alarm text, indicator colour, timing and whether it persists." },
    { title: "Describe recent changes", body: "Note recent replacements, software updates or configuration changes." },
  ],
  noArticles: "No related technical articles yet", noArticlesDescription: "Browse the technical guides or send a question about this model.",
  partsTitle: "Need a replacement module or supporting equipment?", partsDescription: "Confirm the full model, system configuration and compatibility requirements before enquiring about suitable products.", partsAction: "Ask about suitable products",
  inquirySubject: "Technical support enquiry", inquiryPage: "Reference page",
};

const ru: SupportCopy = {
  title: "Техническая поддержка и диагностика",
  description: "Находите сведения об оборудовании и технические руководства по модели для разбора проблем на объекте.",
  home: "Главная", support: "Поддержка", search: "Найти", searching: "Поиск…",
  searchLabel: "Поиск оборудования и технической информации", searchPlaceholder: "Модель, оборудование или вопрос",
  searchHint: "Поиск моделей учитывает различия в пробелах и дефисах.",
  brand: "Бренд", allBrands: "Все бренды", type: "Тип оборудования", allTypes: "Все типы", filters: "Фильтры", clear: "Сбросить фильтры",
  devices: "Поддержка по оборудованию", devicesDescription: "Выберите устройство, изучите его данные и задайте технический вопрос.",
  deviceCount: "устройств", device: "Модель оборудования", resources: "Доступные материалы", open: "К материалам",
  productData: "Данные о продукции", technicalArticles: "Технические статьи", previous: "Назад", next: "Далее", pagination: "Страницы оборудования",
  noResults: "Подходящее оборудование не найдено", noResultsDescription: "Сократите название модели или сбросьте фильтры. Можно также передать данные с заводской таблички и описание проблемы.",
  articlesTitle: "Руководства и справочные материалы", articlesDescription: "Статьи о подборе оборудования, интерфейсах и техническом обслуживании.", allArticles: "Все статьи",
  contactTitle: "Есть модель и проблема на объекте?", contactDescription: "Укажите точную модель, исходный текст аварии и наблюдаемые симптомы для подбора материалов и уточнения совместимости.", contact: "Запросить техподдержку",
  detailSuffix: "Информация и поддержка", contents: "На этой странице", overview: "Данные оборудования", alarms: "Аварии и диагностика", prepare: "Данные с объекта", related: "Технические статьи по теме",
  model: "Модель оборудования", category: "Тип оборудования", version: "Версия контроллера / ПО", versionPlaceholder: "Укажите версию, если она видна в интерфейсе",
  versionUnknown: "Уточняется по установленному оборудованию", productLink: "Все характеристики продукции", source: "Данные каталога", sourceDescription: "Ниже приведены сведения из каталога продукции. Контроллер, версию ПО и конфигурацию установленного оборудования необходимо уточнять отдельно.",
  alarmCode: "Код / название аварии", led: "Индикация", cause: "Возможная причина", procedure: "Диагностика",
  noAlarms: "Открытого руководства по авариям этой модели пока нет", noAlarmsDescription: "Передайте исходный текст аварии и версию контроллера для поиска подходящих материалов. Определения аварий и порядок действий могут зависеть от версии.",
  prepareDescription: "Запишите информацию из доступного интерфейса. Электрические измерения, разборку и замену должны выполнять квалифицированные специалисты по руководству производителя для данной модели.",
  alarmLabel: "Текст аварии или наблюдаемые симптомы", alarmPlaceholder: "Полный текст аварии, время появления и затронутое оборудование",
  contextHelp: "Модель и эти сведения будут добавлены в форму запроса. Перед отправкой их можно дополнить.",
  notes: [
    { title: "Уточните модель", body: "Запишите данные с таблички, модель системы, контроллера или модуля." },
    { title: "Сохраните данные аварии", body: "Запишите полный текст, цвет индикатора, время и постоянство аварии." },
    { title: "Опишите изменения", body: "Укажите недавнюю замену оборудования, обновление ПО или изменение настроек." },
  ],
  noArticles: "Связанных технических статей пока нет", noArticlesDescription: "Ознакомьтесь с руководствами или задайте вопрос об этой модели.",
  partsTitle: "Нужен сменный модуль или дополнительное оборудование?", partsDescription: "Перед запросом уточните полную модель, конфигурацию системы и требования к совместимости.", partsAction: "Запросить подбор продукции",
  inquirySubject: "Запрос технической поддержки", inquiryPage: "Страница материалов",
};

export const supportCopy: Record<Locale, SupportCopy> = { zh, en, ru, fr: en, de: en, es: en, ar: en };
