import type { Locale } from "@/types/domain";

const zh = {
  title: "技术支持与故障排查",
  description: "从设备型号出发，查找产品资料与技术指南，让现场问题有据可循。",
  home: "首页", support: "技术支持", search: "搜索", searching: "正在查找…",
  searchLabel: "查找设备与技术资料", searchPlaceholder: "输入型号、设备名称或问题关键词",
  searchHint: "支持型号中的空格、连字符等不同写法。",
  brand: "品牌", allBrands: "全部品牌", type: "设备类型", allTypes: "全部类型", filters: "筛选条件", clear: "清除筛选",
  devices: "按设备查找支持", devicesDescription: "选择设备，查看型号资料并提交具体的技术问题。",
  deviceCount: "个设备", device: "设备型号", resources: "可用资料", open: "查看支持",
  productData: "产品资料", technicalArticles: "技术文章", previous: "上一页", next: "下一页", pagination: "设备列表分页",
  noResults: "没有找到匹配的设备", noResultsDescription: "试试更短的型号或清除筛选，也可以直接向我们提供设备铭牌与问题描述。",
  articlesTitle: "技术指南与参考", articlesDescription: "从已有技术文章中了解设备选型、接口与日常维护。", allArticles: "查看全部文章",
  contactTitle: "有设备型号，也有现场问题？", contactDescription: "提供准确型号、告警原文和现场现象，便于核对资料与适配条件。", contact: "提交技术咨询",
  detailSuffix: "设备资料与技术支持", contents: "本页目录", overview: "设备信息", alarms: "告警与排查资料", prepare: "提交现场信息", related: "相关技术文章",
  model: "设备型号", category: "设备类型", version: "控制器 / 软件版本", versionPlaceholder: "如能从现有界面查看，请填写版本",
  versionUnknown: "需根据现场设备确认", productLink: "查看完整产品参数", source: "资料入口", sourceDescription: "以下为当前产品目录资料。现场设备的控制器、软件版本和配置仍需另行核对。",
  alarmCode: "告警代码 / 名称", led: "指示灯状态", cause: "可能原因", procedure: "排查方法",
  noAlarms: "该型号暂未收录公开的告警排查手册", noAlarmsDescription: "请提供告警原文与控制器版本，以便确认适用资料。不同版本的告警定义和处理方式可能不同。",
  prepareDescription: "记录现有界面可见的信息即可。电气测量、拆机与更换操作应按对应原厂手册由合格人员执行。",
  alarmLabel: "告警原文或现场现象", alarmPlaceholder: "例如：屏幕显示的完整告警文字、出现时间、受影响的设备",
  contextHelp: "这些信息将随型号一起带入咨询表单，你可以在提交前补充。",
  notes: [
    { title: "确认准确型号", body: "记录设备铭牌、系统型号，以及控制器或模块型号。" },
    { title: "保留告警信息", body: "记录完整告警文字、指示灯颜色、出现时间及是否持续。" },
    { title: "说明现场变化", body: "说明近期是否更换设备、升级软件或调整配置。" },
  ],
  noArticles: "暂无关联的技术文章", noArticlesDescription: "可以浏览技术指南，或就该型号提交具体问题。",
  partsTitle: "需要更换模块或配套设备？", partsDescription: "请先确认完整型号、系统配置与兼容条件，再咨询适配产品。", partsAction: "咨询适配产品",
  inquirySubject: "技术支持咨询", inquiryPage: "资料页面",
  manualNoticeTitle: "获取完整运维与告警排查手册",
  manualNoticeDescription: "本页面仅列出日常现场维护中遇到概率最高的核心告警项。针对设备完整的全量原厂排障代码、板卡级维修指南、深度电气接线图及固件配置手册，我们将在正式订单确认或设备交付后，向采购客户随箱提供完整电子技术文档与专属 FAE 工程师技术支持。",
  manualNoticeAction: "联系客户经理获取完整手册",

};

type SupportCopy = { [K in keyof typeof zh]: K extends "notes" ? Array<{ title: string; body: string }> : string };

const en: SupportCopy = {
  title: "Support & Troubleshooting",
  description: "Find equipment information and technical guides by model, and bring clarity to on-site issues.",
  home: "Home", support: "Support", search: "Search", searching: "Searching…",
  searchLabel: "Find equipment and technical information", searchPlaceholder: "Search a model, device or topic",
  searchHint: "Model searches also match variations in spacing and hyphens.",
  brand: "Brand", allBrands: "All brands", type: "Equipment type", allTypes: "All types", filters: "Filters", clear: "Clear filters",
  devices: "Find support by equipment", devicesDescription: "Choose a device to view its information and ask a specific technical question.",
  deviceCount: "devices", device: "Equipment model", resources: "Available resources", open: "View support",
  productData: "Product information", technicalArticles: "Technical articles", previous: "Previous", next: "Next", pagination: "Equipment pages",
  noResults: "No matching equipment", noResultsDescription: "Try a shorter model name or clear the filters. You can also send us the nameplate details and a description of the issue.",
  articlesTitle: "Technical guides & references", articlesDescription: "Explore published articles on equipment selection, interfaces and maintenance.", allArticles: "View all articles",
  contactTitle: "Have a model and an on-site issue?", contactDescription: "Share the exact model, alarm text and observed symptoms to help identify relevant information and compatibility requirements.", contact: "Request technical support",
  detailSuffix: "Equipment information & support", contents: "On this page", overview: "Equipment information", alarms: "Alarms & troubleshooting", prepare: "Share on-site information", related: "Related technical articles",
  model: "Equipment model", category: "Equipment type", version: "Controller / software version", versionPlaceholder: "Enter the version if visible in the existing interface",
  versionUnknown: "Confirm against the installed equipment", productLink: "View full product specifications", source: "Product reference", sourceDescription: "Information below comes from the current product catalogue. Confirm the controller, software version and configuration of the installed equipment separately.",
  alarmCode: "Alarm code / name", led: "LED status", cause: "Possible cause", procedure: "Troubleshooting",
  noAlarms: "No public alarm guide is available for this model yet", noAlarmsDescription: "Share the original alarm text and controller version to help identify applicable documentation. Alarm definitions and procedures may vary by version.",
  prepareDescription: "Record information visible in the existing interface. Electrical measurements, disassembly and replacement should follow the applicable manufacturer's manual and be performed by qualified personnel.",
  alarmLabel: "Alarm text or observed symptoms", alarmPlaceholder: "Include the complete alarm text, when it appeared and which equipment is affected",
  contextHelp: "Your model and these details will be added to the enquiry form for you to review before sending.",
  notes: [
    { title: "Identify the exact model", body: "Record the nameplate, system model and controller or module model." },
    { title: "Keep the alarm details", body: "Record the full alarm text, indicator colour, timing and whether it persists." },
    { title: "Describe recent changes", body: "Note recent replacements, software updates or configuration changes." },
  ],
  noArticles: "No related technical articles yet", noArticlesDescription: "Browse the technical guides or send a question about this model.",
  partsTitle: "Need a replacement module or supporting equipment?", partsDescription: "Confirm the full model, system configuration and compatibility requirements before enquiring about suitable products.", partsAction: "Ask about suitable products",
  inquirySubject: "Technical support enquiry", inquiryPage: "Reference page",
  manualNoticeTitle: "Access Complete Maintenance & Full Alarm Troubleshooting Manual",
  manualNoticeDescription: "This page lists high-frequency critical alarm codes commonly encountered in field maintenance. Comprehensive manufacturer troubleshooting matrices, board-level repair guides, detailed electrical schematics, and firmware commissioning manuals are delivered alongside equipment upon formal project procurement, accompanied by dedicated FAE technical support.",
  manualNoticeAction: "Contact Account Manager for Full Manual",

};

const ru: SupportCopy = {
  title: "Техническая поддержка и диагностика",
  description: "Находите сведения об оборудовании и технические руководства по модели для разбора проблем на объекте.",
  home: "Главная", support: "Поддержка", search: "Найти", searching: "Поиск…",
  searchLabel: "Поиск оборудования и технической информации", searchPlaceholder: "Модель, оборудование или вопрос",
  searchHint: "Поиск моделей учитывает различия в пробелах и дефисах.",
  brand: "Бренд", allBrands: "Все бренды", type: "Тип оборудования", allTypes: "Все типы", filters: "Фильтры", clear: "Сбросить фильтры",
  devices: "Поддержка по оборудованию", devicesDescription: "Выберите устройство, изучите его данные и задайте технический вопрос.",
  deviceCount: "устройств", device: "Модель оборудования", resources: "Доступные материалы", open: "К материалам",
  productData: "Данные о продукции", technicalArticles: "Технические статьи", previous: "Назад", next: "Далее", pagination: "Страницы оборудования",
  noResults: "Подходящее оборудование не найдено", noResultsDescription: "Сократите название модели или сбросьте фильтры. Можно также передать данные с заводской таблички и описание проблемы.",
  articlesTitle: "Руководства и справочные материалы", articlesDescription: "Статьи о подборе оборудования, интерфейсах и техническом обслуживании.", allArticles: "Все статьи",
  contactTitle: "Есть модель и проблема на объекте?", contactDescription: "Укажите точную модель, исходный текст аварии и наблюдаемые симптомы для подбора материалов и уточнения совместимости.", contact: "Запросить техподдержку",
  detailSuffix: "Информация и поддержка", contents: "На этой странице", overview: "Данные оборудования", alarms: "Аварии и диагностика", prepare: "Данные с объекта", related: "Технические статьи по теме",
  model: "Модель оборудования", category: "Тип оборудования", version: "Версия контроллера / ПО", versionPlaceholder: "Укажите версию, если она видна в интерфейсе",
  versionUnknown: "Уточняется по установленному оборудованию", productLink: "Все характеристики продукции", source: "Данные каталога", sourceDescription: "Ниже приведены сведения из каталога продукции. Контроллер, версию ПО и конфигурацию установленного оборудования необходимо уточнять отдельно.",
  alarmCode: "Код / название аварии", led: "Индикация", cause: "Возможная причина", procedure: "Диагностика",
  noAlarms: "Открытого руководства по авариям этой модели пока нет", noAlarmsDescription: "Передайте исходный текст аварии и версию контроллера для поиска подходящих материалов. Определения аварий и порядок действий могут зависеть от версии.",
  prepareDescription: "Запишите информацию из доступного интерфейса. Электрические измерения, разборку и замену должны выполнять квалифицированные специалисты по руководству производителя для данной модели.",
  alarmLabel: "Текст аварии или наблюдаемые симптомы", alarmPlaceholder: "Полный текст аварии, время появления и затронутое оборудование",
  contextHelp: "Модель и эти сведения будут добавлены в форму запроса. Перед отправкой их можно дополнить.",
  notes: [
    { title: "Уточните модель", body: "Запишите данные с таблички, модель системы, контроллера или модуля." },
    { title: "Сохраните данные аварии", body: "Запишите полный текст, цвет индикатора, время и постоянство аварии." },
    { title: "Опишите изменения", body: "Укажите недавнюю замену оборудования, обновление ПО или изменение настроек." },
  ],
  noArticles: "Связанных технических статей пока нет", noArticlesDescription: "Ознакомьтесь с руководствами или задайте вопрос об этой модели.",
  partsTitle: "Нужен сменный модуль или дополнительное оборудование?", partsDescription: "Перед запросом уточните полную модель, конфигурацию системы и требования к совместимости.", partsAction: "Запросить подбор продукции",
  inquirySubject: "Запрос технической поддержки", inquiryPage: "Страница материалов",
  manualNoticeTitle: "Получить полное руководство по эксплуатации и устранению аварий",
  manualNoticeDescription: "На этой странице приведены только наиболее часто встречающиеся аварийные сигналы при полевом обслуживании. Полные заводские матрицы кодов неисправностей, покомпонентные схемы и регламенты настройки поставляются клиентам в составе проектной документации при закупке оборудования с поддержкой инженеров FAE.",
  manualNoticeAction: "Запросить полное руководство у менеджера",

};

const ar: SupportCopy = {
  "title": "الدعم الفني واستكشاف الأعطال",
  "description": "ابحث عن بيانات المعدات والأدلة الفنية حسب الطراز، وحل المشكلات الميدانية بدقة وموثوقية.",
  "home": "الرئيسية",
  "support": "الدعم الفني",
  "search": "بحث",
  "searching": "جارٍ البحث…",
  "searchLabel": "البحث عن المعدات والمعلومات الفنية",
  "searchPlaceholder": "ابحث حسب الطراز أو الجهاز أو الموضوع",
  "searchHint": "يشمل البحث عن الطراز التغييرات في المسافات وعلامات الربط (-).",
  "brand": "العلامة التجارية",
  "allBrands": "جميع العلامات التجارية",
  "type": "نوع المعدات",
  "allTypes": "جميع الأنواع",
  "filters": "عوامل التصفية",
  "clear": "إعادة ضبط التصفية",
  "devices": "البحث عن الدعم حسب المعدة",
  "devicesDescription": "حدد جهازًا لعرض مواصفاته وطرح استفسار فني محدد بشأنه.",
  "deviceCount": "أجهزة",
  "device": "طراز الجهاز",
  "resources": "الموارد المتاحة",
  "open": "عرض الدعم",
  "productData": "بيانات المنتج",
  "technicalArticles": "المقالات الفنية",
  "previous": "السابق",
  "next": "التالي",
  "pagination": "صفحات المعدات",
  "noResults": "لا توجد معدات مطابقة",
  "noResultsDescription": "جرّب استخدام اسم طراز أقصر أو أعد ضبط عوامل التصفية. يمكنك أيضًا إرسال بيانات لوحة البيانات (Nameplate) ووصفًا للعطل.",
  "articlesTitle": "الأدلة والمراجع الفنية",
  "articlesDescription": "استكشف المقالات المنشورة حول اختيار المعدات، والواجهات، والصيانة التشغيلية.",
  "allArticles": "عرض كافة المقالات",
  "contactTitle": "هل لديك طراز محدد وتواجه مشكلة في الموقع؟",
  "contactDescription": "يرجى تزويدنا بالطراز الدقيق، ونص الإنذار، والأعراض المرصودة للمساعدة في تحديد الوثائق ومتطلبات التوافق ذات الصلة.",
  "contact": "طلب دعم فني",
  "detailSuffix": "بيانات المعدة والدعم الفني",
  "contents": "في هذه الصفحة",
  "overview": "بيانات المعدة",
  "alarms": "الإنذارات واستكشاف الأعطال",
  "prepare": "مشاركة البيانات الميدانية",
  "related": "مقالات فنية ذات صلة",
  "model": "طراز الجهاز",
  "category": "نوع المعدات",
  "version": "إصدار وحدة التحكم / البرمجيات",
  "versionPlaceholder": "أدخل الإصدار إذا كان ظاهرًا في واجهة التشغيل الحالية",
  "versionUnknown": "يُرجى التحقق مباشرة من المعدات المثبتة",
  "productLink": "عرض المواصفات الفنية الكاملة للمنتج",
  "source": "مرجع المنتج",
  "sourceDescription": "المعلومات الواردة أدناه مأخوذة من كتالوج المنتجات الحالي. يُرجى التحقق من وحدة التحكم، وإصدار البرمجيات، والتكوين الفعلي للمعدات المركبة بشكل مستقل.",
  "alarmCode": "رمز / مسمى الإنذار",
  "led": "حالة مؤشرات LED",
  "cause": "السبب المحتمل",
  "procedure": "إجراءات المعالجة واستكشاف الأعطال",
  "noAlarms": "لا يتوفر دليل إنذارات عام لهذا الطراز حتى الآن",
  "noAlarmsDescription": "يرجى تزويدنا بالنص الأصلي للإنذار وإصدار وحدة التحكم لتحديد الوثائق المناسبة. قد تختلف تعريفات الإنذارات وإجراءات معالجتها بحسب الإصدار.",
  "prepareDescription": "سجّل البيانات الظاهرة على واجهة النظام الحالية. يجب أن تتم القياسات الكهربائية، وأعمال الفك والاستبدال وفقًا لدليل الشركة المصنعة وعلى يد فنيين مؤهلين.",
  "alarmLabel": "نص الإنذار أو الأعراض الملاحظة",
  "alarmPlaceholder": "اذكر النص الكامل للإنذار، وتوقيت ظهوره، والمعدة المتأثرة به",
  "contextHelp": "سيتم تضمين الطراز وهذه التفاصيل في نموذج الاستفسار لمراجعتها قبل الإرسال.",
  "notes": [
    {
      "title": "تحديد الطراز الدقيق",
      "body": "سجّل بيانات اللوحة الاسمية (Nameplate)، وطراز النظام، وطراز وحدة التحكم أو الوحدة النمطية."
    },
    {
      "title": "الاحتفاظ بتفاصيل الإنذار",
      "body": "سجّل النص الكامل للإنذار، ولون المؤشرات الضوئية، وتوقيت الحدوث، وما إذا كان الإنذار مستمرًا."
    },
    {
      "title": "توثيق التغييرات الأخيرة",
      "body": "دوّن أي عمليات استبدال حديثة، أو ترقيات برمجية، أو تعديلات في التكوين."
    }
  ],
  "noArticles": "لا توجد مقالات فنية ذات صلة حتى الآن",
  "noArticlesDescription": "تصفح الأدلة الفنية أو أرسل استفسارًا حول هذا الطراز.",
  "partsTitle": "هل تحتاج إلى وحدة بديلة أو معدات مساعدة؟",
  "partsDescription": "تأكد من مطابقة الطراز بالكامل، وتكوين النظام، ومتطلبات التوافق قبل الاستفسار عن المنتجات البديلة المناسبة.",
  "partsAction": "الاستفسار عن المنتجات المتوافقة",
  "inquirySubject": "طلب دعم فني",
  "inquiryPage": "الصفحة المرجعية",
  "manualNoticeTitle": "الحصول على الدليل الكامل للتشغيل ومعالجة كافة الإنذارات",
  "manualNoticeDescription": "تعرض هذه الصفحة فقط إنذارات الأعطال الميدانية الأكثر شيوعاً. أما مصفوفة رموز الأعطال المصنعية الشاملة، ومخططات الدوائر الكهربائية وأدلة الضبط المتقدمة، فيتم توفيرها لعملائنا كوثائق رسمية مرافقة لتسليم المعدات مع دعم فني هندسي مخصص.",
  "manualNoticeAction": "التواصل مع مسؤول الحساب للحصول على الدليل الكامل"
};

const fr: SupportCopy = {
  "title": "Support technique et dépannage",
  "description": "Consultez les informations sur les équipements et les guides techniques par modèle, et résolvez efficacement les incidents sur site.",
  "home": "Accueil",
  "support": "Support",
  "search": "Rechercher",
  "searching": "Recherche en cours…",
  "searchLabel": "Rechercher des équipements et des informations techniques",
  "searchPlaceholder": "Rechercher un modèle, un équipement ou un sujet",
  "searchHint": "La recherche par modèle prend également en compte les variantes d'espaces et de tirets.",
  "brand": "Marque",
  "allBrands": "Toutes les marques",
  "type": "Type d'équipement",
  "allTypes": "Tous les types",
  "filters": "Filtres",
  "clear": "Effacer les filtres",
  "devices": "Support par équipement",
  "devicesDescription": "Sélectionnez un équipement pour consulter ses spécifications et soumettre une question technique ciblée.",
  "deviceCount": "équipements",
  "device": "Modèle d'équipement",
  "resources": "Ressources disponibles",
  "open": "Consulter le support",
  "productData": "Fiche produit",
  "technicalArticles": "Articles techniques",
  "previous": "Précédent",
  "next": "Suivant",
  "pagination": "Pages d'équipements",
  "noResults": "Aucun équipement correspondant",
  "noResultsDescription": "Essayez avec une référence plus courte ou réinitialisez les filtres. Vous pouvez également nous transmettre les données de la plaque signalétique ainsi qu'une description de l'incident.",
  "articlesTitle": "Guides techniques et documentations de référence",
  "articlesDescription": "Consultez nos publications sur la sélection d'équipements, le raccordement d'interfaces et la maintenance.",
  "allArticles": "Tous les articles",
  "contactTitle": "Vous rencontrez un incident sur site avec un modèle précis ?",
  "contactDescription": "Transmettez-nous la référence exacte, le libellé de l'alarme et les symptômes observés afin d'identifier la documentation pertinente et les exigences de compatibilité.",
  "contact": "Demander une assistance technique",
  "detailSuffix": "Informations équipement & support",
  "contents": "Au sommaire",
  "overview": "Informations sur l'équipement",
  "alarms": "Alarmes et résolution de pannes",
  "prepare": "Renseigner les données de site",
  "related": "Articles techniques associés",
  "model": "Modèle d'équipement",
  "category": "Type d'équipement",
  "version": "Version du contrôleur / logiciel",
  "versionPlaceholder": "Saisir la version affichée sur l'interface actuelle",
  "versionUnknown": "À vérifier directement sur l'équipement installé",
  "productLink": "Voir les spécifications techniques complètes",
  "source": "Référence produit",
  "sourceDescription": "Les données ci-dessous sont issues du catalogue produit en cours. Vérifiez le contrôleur, la version logicielle et la configuration sur site de l'équipement installé.",
  "alarmCode": "Code / Désignation de l'alarme",
  "led": "État des voyants LED",
  "cause": "Cause probable",
  "procedure": "Procédure de dépannage",
  "noAlarms": "Aucun guide public d'alarmes disponible pour ce modèle à ce jour",
  "noAlarmsDescription": "Transmettez-nous le texte original de l'alarme et la version du contrôleur pour obtenir la documentation applicable. La signification des alarmes et les procédures peuvent varier selon les versions.",
  "prepareDescription": "Relevez les informations visibles sur l'interface du système. Les mesures électriques, démontages et remplacements doivent se conformer au manuel constructeur et être effectués par du personnel qualifié.",
  "alarmLabel": "Texte de l'alarme ou symptômes observés",
  "alarmPlaceholder": "Indiquez l'intitulé complet de l'alarme, l'heure d'apparition et l'équipement concerné",
  "contextHelp": "Le modèle et ces informations seront intégrés au formulaire de demande pour relecture avant envoi.",
  "notes": [
    {
      "title": "Identifier le modèle exact",
      "body": "Relevez la plaque signalétique, la référence du châssis ou du système et la désignation du contrôleur ou des modules."
    },
    {
      "title": "Conserver les détails d'alarme",
      "body": "Notez le libellé exact de l'alarme, la couleur des voyants, l'horodatage et la persistance de l'état d'erreur."
    },
    {
      "title": "Décrire les modifications récentes",
      "body": "Signalez tout remplacement récent de composant, mise à jour logicielle ou modification de paramétrage."
    }
  ],
  "noArticles": "Aucun article technique associé pour le moment",
  "noArticlesDescription": "Parcourez les guides techniques ou posez une question relative à ce modèle.",
  "partsTitle": "Besoin d'un module de remplacement ou d'équipements complémentaires ?",
  "partsDescription": "Vérifiez la référence complète, la configuration du système et les contraintes de compatibilité avant toute demande de pièces adaptées.",
  "partsAction": "Demander conseil pour le matériel compatible",
  "inquirySubject": "Demande de support technique",
  "inquiryPage": "Page de référence",
  "manualNoticeTitle": "Accéder au manuel complet d'exploitation et de dépannage",
  "manualNoticeDescription": "Cette page ne répertorie que les alarmes critiques les plus fréquentes sur site. Les matrices d'alarmes constructeur complètes, les schémas électriques détaillés et les manuels de configuration avancés sont remis aux clients lors de la livraison du projet, avec l'accompagnement de nos ingénieurs FAE dédiés.",
  "manualNoticeAction": "Contacter un conseiller pour le manuel complet"
};

const de: SupportCopy = {
  "title": "Support & Fehlerbehebung",
  "description": "Finden Sie Geräteinformationen und technische Leitfäden nach Modell, um Störungen vor Ort gezielt zu analysieren und zu beheben.",
  "home": "Startseite",
  "support": "Support",
  "search": "Suchen",
  "searching": "Suche läuft…",
  "searchLabel": "Geräte und technische Informationen suchen",
  "searchPlaceholder": "Nach Modell, Komponente oder Thema suchen",
  "searchHint": "Die Modellsuche berücksichtigt auch abweichende Schreibweisen mit Leerzeichen oder Bindestrichen.",
  "brand": "Hersteller",
  "allBrands": "Alle Hersteller",
  "type": "Gerätetyp",
  "allTypes": "Alle Typen",
  "filters": "Filter",
  "clear": "Filter zurücksetzen",
  "devices": "Support nach Gerät",
  "devicesDescription": "Wählen Sie eine Komponente, um Gerätedaten einzusehen und gezielte technische Anfragen zu stellen.",
  "deviceCount": "Geräte",
  "device": "Gerätemodell",
  "resources": "Verfügbare Ressourcen",
  "open": "Support anzeigen",
  "productData": "Produktinformationen",
  "technicalArticles": "Fachartikel",
  "previous": "Zurück",
  "next": "Weiter",
  "pagination": "Geräteseiten",
  "noResults": "Keine passenden Geräte gefunden",
  "noResultsDescription": "Verkürzen Sie den Modellnamen oder setzen Sie die Filter zurück. Alternativ können Sie uns die Typenschilddaten und eine Fehlerbeschreibung zusenden.",
  "articlesTitle": "Technische Leitfäden & Referenzen",
  "articlesDescription": "Entdecken Sie Fachbeiträge zu Geräteauswahl, Schnittstellen und Instandhaltung.",
  "allArticles": "Alle Artikel anzeigen",
  "contactTitle": "Sie haben ein konkretes Modell und eine Störung vor Ort?",
  "contactDescription": "Übermitteln Sie das genaue Modell, den Alarmtext sowie beobachtete Symptome, um relevante Dokumentationen und Kompatibilitätsanforderungen zu ermitteln.",
  "contact": "Technischen Support anfordern",
  "detailSuffix": "Geräteinformationen & Support",
  "contents": "Auf dieser Seite",
  "overview": "Geräteübersicht",
  "alarms": "Alarme & Störungsbehebung",
  "prepare": "Vor-Ort-Daten erfassen",
  "related": "Verwandte Fachartikel",
  "model": "Gerätemodell",
  "category": "Gerätetyp",
  "version": "Controller- / Firmware-Version",
  "versionPlaceholder": "Version eingeben, falls auf der Benutzeroberfläche ersichtlich",
  "versionUnknown": "Am installierten System abzugleichen",
  "productLink": "Vollständige Produktspezifikationen anzeigen",
  "source": "Produktreferenz",
  "sourceDescription": "Die nachstehenden Daten entstammen dem aktuellen Produktkatalog. Controller, Softwareversion und Konfiguration des installierten Systems sind separat abzugleichen.",
  "alarmCode": "Alarmcode / -bezeichnung",
  "led": "LED-Status",
  "cause": "Mögliche Ursache",
  "procedure": "Fehlerbehebung",
  "noAlarms": "Für dieses Modell liegt noch kein öffentlicher Alarmleitfaden vor",
  "noAlarmsDescription": "Teilen Sie uns den originalen Alarmtext und die Controller-Version mit, um passende Unterlagen bereitzustellen. Alarmdefinitionen und Verfahren können je nach Version variieren.",
  "prepareDescription": "Erfassen Sie alle in der Systemoberfläche sichtbaren Parameter. Elektrische Messungen, Demontagen und Komponententausche müssen nach Herstellervorgaben und durch qualifiziertes Fachpersonal erfolgen.",
  "alarmLabel": "Alarmtext oder aufgetretene Symptome",
  "alarmPlaceholder": "Geben Sie den vollständigen Alarmtext an sowie den Zeitpunkt des Auftretens und betroffene Komponenten",
  "contextHelp": "Ihr Modell und diese Angaben werden in das Anfrageformular übernommen, damit Sie sie vor dem Absenden prüfen können.",
  "notes": [
    {
      "title": "Exaktes Modell identifizieren",
      "body": "Erfassen Sie die Daten vom Typenschild, das Systemmodell sowie die Bezeichnung von Controller und Baugruppen."
    },
    {
      "title": "Alarmdetails festhalten",
      "body": "Notieren Sie den vollständigen Alarmtext, LED-Signalfarben, den Zeitpunkt und ob der Fehler dauerhaft ansteht."
    },
    {
      "title": "Kürzliche Änderungen dokumentieren",
      "body": "Erfassen Sie kürzlich durchgeführte Komponententausche, Softwareupdates oder Konfigurationsänderungen."
    }
  ],
  "noArticles": "Noch keine Fachartikel zu diesem Gerät vorhanden",
  "noArticlesDescription": "Durchsuchen Sie unsere technischen Leitfäden oder senden Sie eine Anfrage zu diesem Modell.",
  "partsTitle": "Benötigen Sie ein Ersatzmodul oder Zusatzequipment?",
  "partsDescription": "Gleichen Sie die vollständige Modellbezeichnung, Systemkonfiguration und Kompatibilitätsvorgaben ab, bevor Sie passende Ersatzteile anfragen.",
  "partsAction": "Passende Produkte anfragen",
  "inquirySubject": "Supportanfrage Technik",
  "inquiryPage": "Referenzseite",
  "manualNoticeTitle": "Vollständiges Betriebs- und Störungsbehebungshandbuch anfordern",
  "manualNoticeDescription": "Diese Seite führt die im Feldeinsatz am häufigsten auftretenden kritischen Alarmcodes auf. Vollständige Hersteller-Fehlercodematrizen, detaillierte Schaltpläne und Firmware-Konfigurationshandbücher werden autorisierten Kunden bei Projektbeschaffung und Auslieferung zusammen mit dediziertem FAE-Support bereitgestellt.",
  "manualNoticeAction": "Kundenberater für vollständiges Handbuch kontaktieren"
};

const es: SupportCopy = {
  "title": "Soporte técnico y resolución de problemas",
  "description": "Consulte información de equipos y guías técnicas por modelo para diagnosticar y resolver incidencias en sitio de manera ágil.",
  "home": "Inicio",
  "support": "Soporte",
  "search": "Buscar",
  "searching": "Buscando…",
  "searchLabel": "Buscar equipos e información técnica",
  "searchPlaceholder": "Buscar un modelo, equipo o tema",
  "searchHint": "La búsqueda de modelos también contempla variaciones en espacios y guiones.",
  "brand": "Marca",
  "allBrands": "Todas las marcas",
  "type": "Tipo de equipo",
  "allTypes": "Todos los tipos",
  "filters": "Filtros",
  "clear": "Restablecer filtros",
  "devices": "Soporte por equipo",
  "devicesDescription": "Seleccione un equipo para ver sus especificaciones y formular una consulta técnica específica.",
  "deviceCount": "equipos",
  "device": "Modelo de equipo",
  "resources": "Recursos disponibles",
  "open": "Ver soporte",
  "productData": "Ficha del producto",
  "technicalArticles": "Artículos técnicos",
  "previous": "Anterior",
  "next": "Siguiente",
  "pagination": "Páginas de equipos",
  "noResults": "No se encontraron equipos coincidentes",
  "noResultsDescription": "Pruebe con un nombre de modelo más corto o restablezca los filtros. También puede enviarnos los datos de la placa de características y una descripción del problema.",
  "articlesTitle": "Guías técnicas y documentación de referencia",
  "articlesDescription": "Explore artículos publicados sobre selección de equipos, interfaces y procedimientos de mantenimiento.",
  "allArticles": "Ver todos los artículos",
  "contactTitle": "¿Tiene un modelo específico y una incidencia en sitio?",
  "contactDescription": "Indique el modelo exacto, el texto de la alarma y los síntomas observados para localizar la documentación técnica y los requisitos de compatibilidad.",
  "contact": "Solicitar soporte técnico",
  "detailSuffix": "Información del equipo y soporte",
  "contents": "En esta página",
  "overview": "Información del equipo",
  "alarms": "Alarmas y resolución de averías",
  "prepare": "Recopilar datos de sitio",
  "related": "Artículos técnicos relacionados",
  "model": "Modelo de equipo",
  "category": "Tipo de equipo",
  "version": "Versión de controlador / software",
  "versionPlaceholder": "Indique la versión visible en la interfaz operativa actual",
  "versionUnknown": "Verificar directamente en el equipo instalado",
  "productLink": "Ver especificaciones técnicas completas",
  "source": "Referencia del producto",
  "sourceDescription": "La información siguiente procede del catálogo vigente. Se debe verificar de forma independiente el controlador, la versión de software y la configuración del equipo instalado.",
  "alarmCode": "Código / descripción de alarma",
  "led": "Estado de los LED",
  "cause": "Causa probable",
  "procedure": "Procedimiento de diagnóstico y solución",
  "noAlarms": "Aún no hay una guía pública de alarmas para este modelo",
  "noAlarmsDescription": "Comparta el texto original de la alarma y la versión del controlador para identificar la documentación correspondiente. Las definiciones de alarma y los procedimientos pueden variar según la versión.",
  "prepareDescription": "Registre los datos visibles en la interfaz del sistema. Las mediciones eléctricas, desmontajes y sustituciones deben realizarse conforme al manual del fabricante y por personal técnico cualificado.",
  "alarmLabel": "Texto de la alarma o síntomas detectados",
  "alarmPlaceholder": "Indique el texto íntegro de la alarma, cuándo ocurrió y qué equipos se ven afectados",
  "contextHelp": "El modelo y estos detalles se incorporarán al formulario de consulta para su revisión antes del envío.",
  "notes": [
    {
      "title": "Identificar el modelo exacto",
      "body": "Anote los datos de la placa de características, el modelo del bastidor o sistema y la referencia del controlador o módulo."
    },
    {
      "title": "Registrar los detalles de la alarma",
      "body": "Anote el texto completo de la alarma, el color de los indicadores lumínicos, el momento de aparición y si la condición persiste."
    },
    {
      "title": "Detallar cambios recientes",
      "body": "Indique sustituciones recientes de componentes, actualizaciones de firmware o modificaciones de configuración."
    }
  ],
  "noArticles": "No hay artículos técnicos relacionados por el momento",
  "noArticlesDescription": "Consulte las guías técnicas o envíe una consulta sobre este modelo.",
  "partsTitle": "¿Necesita un módulo de repuesto o equipos auxiliares?",
  "partsDescription": "Verifique el modelo exacto, la configuración del sistema y los requerimientos de compatibilidad antes de solicitar repuestos adecuados.",
  "partsAction": "Consultar por productos compatibles",
  "inquirySubject": "Consulta de soporte técnico",
  "inquiryPage": "Página de referencia",
  "manualNoticeTitle": "Acceso al manual completo de mantenimiento y resolución de alarmas",
  "manualNoticeDescription": "Esta página solo detalla las alarmas críticas más frecuentes en campo. Las matrices completas de códigos del fabricante, guías de reparación y esquemas eléctricos se entregan a los clientes con la adjudicación y entrega del proyecto, respaldados por nuestro equipo de ingenieros FAE.",
  "manualNoticeAction": "Contactar a un asesor para el manual completo"
};

export const supportCopy: Record<Locale, SupportCopy> = { zh, en, ru, fr, de, es, ar };
