"use client";

import { useCallback, useEffect, useId, useRef, useState } from "react";
import { ArrowRightIcon, ChevronLeftIcon, ChevronRightIcon } from "lucide-react";
import { Link } from "@/i18n/navigation";
import { ProductPreviewCard } from "@/components/products/product-card";
import type { Locale } from "@/types/domain";
import type { HomeProductGroupView } from "@/types/home-products";
import styles from "./home-product-carousel.module.css";

type Labels = { categories: string; previous: string; next: string; viewAll: string; empty: string };

function ProductShelf({ group, locale, labels, surface }: { group: HomeProductGroupView; locale: Locale; labels: Labels; surface: "plain" | "muted" }) {
  const headingId = useId();
  const track = useRef<HTMLUListElement>(null);
  const loadingRef = useRef(false);
  const loadMoreRef = useRef<() => Promise<void>>(async () => undefined);
  const advanceAfterLoadRef = useRef(false);
  const advanceTargetIndexRef = useRef<number | null>(null);
  const skipNearEndUntilRef = useRef(0);
  const [products, setProducts] = useState(group.products);
  const [hasMore, setHasMore] = useState(group.hasMore);
  const [nextOffset, setNextOffset] = useState(group.products.length);
  const [loading, setLoading] = useState(false);
  const [position, setPosition] = useState({ page: 1, pages: 1 });
  const geometry = useRef({ step: 0, visible: 6, max: 0 });
  const rtl = locale === "ar";

  useEffect(() => {
    const element = track.current;
    if (!element) return;
    const previousMax = geometry.current.max;
    const measure = () => {
      const first = element.firstElementChild?.getBoundingClientRect();
      if (!first) return;
      const gap = parseFloat(getComputedStyle(element).columnGap) || 0;
      const step = first.width + gap;
      // Never round up here: an overestimated visible count makes a page
      // land between card boundaries and leaves a clipped card at each edge.
      const visible = Math.max(1, Math.floor((element.clientWidth + gap + 0.5) / step));
      const max = Math.max(0, element.scrollWidth - element.clientWidth);
      geometry.current = { step, visible, max };
      const pages = Math.max(1, Math.ceil(products.length / visible));
      const offset = Math.abs(element.scrollLeft);
      const page = max > 0 && offset >= max - 2 ? pages : Math.min(pages, Math.round(offset / (step * visible)) + 1);
      setPosition((previous) => previous.page === page && previous.pages === pages ? previous : { page, pages });
    };
    measure();
    if (advanceAfterLoadRef.current) {
      // The new cards are only measurable after React commits them. Move to
      // the newly available row so an end-arrow click always has visible
      // feedback instead of silently appending cards off-screen.
      requestAnimationFrame(() => {
        const nextMax = Math.max(0, element.scrollWidth - element.clientWidth);
        const step = geometry.current.step;
        const targetIndex = advanceTargetIndexRef.current;
        if (nextMax > previousMax && step > 0) {
          // Show the newly appended row immediately. Temporarily ignore the
          // scroll event generated by this programmatic move so one click
          // cannot cascade through every remaining page.
          skipNearEndUntilRef.current = Date.now() + 900;
          const target = targetIndex == null ? nextMax : Math.min(nextMax, targetIndex * step);
          element.scrollTo({ left: target * (rtl ? -1 : 1), behavior: window.matchMedia("(prefers-reduced-motion: reduce)").matches ? "instant" : "smooth" });
        }
        advanceAfterLoadRef.current = false;
        advanceTargetIndexRef.current = null;
      });
    }
    const observer = new ResizeObserver(measure);
    observer.observe(element);
    element.addEventListener("scroll", measure, { passive: true });
    return () => { observer.disconnect(); element.removeEventListener("scroll", measure); };
  }, [products.length, rtl]);

  const loadMore = useCallback(async () => {
    if (!hasMore || loadingRef.current) return;
    loadingRef.current = true;
    setLoading(true);
    try {
      const params = new URLSearchParams({ locale, category: group.key, offset: String(nextOffset), limit: "6" });
      const response = await fetch(`/api/home-products?${params.toString()}`, { headers: { Accept: "application/json" } });
      if (!response.ok) return;
      const page = await response.json() as { products?: typeof products; hasMore?: boolean; nextOffset?: number | null };
      const incoming = Array.isArray(page.products) ? page.products : [];
      setProducts((current) => {
        const existing = new Set(current.map((product) => product.id));
        return [...current, ...incoming.filter((product) => product && !existing.has(product.id))];
      });
      setHasMore(Boolean(page.hasMore));
      setNextOffset(typeof page.nextOffset === "number" ? page.nextOffset : nextOffset + incoming.length);
    } catch {
      // A failed prefetch should not interrupt scrolling; a later arrow/scroll can retry.
    } finally {
      loadingRef.current = false;
      setLoading(false);
    }
  }, [group.key, hasMore, locale, nextOffset]);

  useEffect(() => {
    loadMoreRef.current = loadMore;
  }, [loadMore]);

  useEffect(() => {
    const element = track.current;
    if (!element) return;
    const onScrollNearEnd = () => {
      const { step } = geometry.current;
      const max = Math.max(0, element.scrollWidth - element.clientWidth);
      const offset = Math.abs(element.scrollLeft);
      if (Date.now() < skipNearEndUntilRef.current) return;
      if (hasMore && max > 0 && offset >= max - Math.max(step * 1.5, 96)) void loadMoreRef.current();
    };
    element.addEventListener("scroll", onScrollNearEnd, { passive: true });
    return () => element.removeEventListener("scroll", onScrollNearEnd);
  }, [hasMore]);

  function move(direction: number) {
    const element = track.current;
    if (!element) return;
    const { step, visible, max } = geometry.current;
    const page = Math.round(Math.abs(element.scrollLeft) / (step * visible));
    if (direction > 0 && hasMore && Math.abs(element.scrollLeft) >= max - 2) {
      advanceAfterLoadRef.current = true;
      advanceTargetIndexRef.current = products.length;
      void loadMore();
      return;
    }
    const offset = Math.max(0, Math.min(max, (page + direction) * step * visible));
    element.scrollTo({ left: offset * (rtl ? -1 : 1), behavior: window.matchMedia("(prefers-reduced-motion: reduce)").matches ? "instant" : "smooth" });
  }

  return <section className={styles.section} aria-labelledby={headingId} data-home-product-category={group.key} data-surface={surface} dir={rtl ? "rtl" : "ltr"}>
    <div className={`page-shell ${styles.inner}`}>
      <h2 id={headingId} className={styles.heading}>{group.name}</h2>
      {group.products.length ? <div className={styles.gallery}>
        <ul ref={track} className={styles.track} aria-label={group.name}>
          {products.map((product) => <li key={product.id}><ProductPreviewCard product={product} locale={locale} /></li>)}
        </ul>
        {position.pages > 1 || hasMore ? <>
          <button className={`${styles.edgeControl} ${styles.edgeStart}`} type="button" onClick={() => move(-1)} disabled={position.page === 1 || loading} aria-label={labels.previous}><ChevronLeftIcon aria-hidden="true" /></button>
          <span className="sr-only" dir="ltr" aria-live="polite" aria-atomic="true">{position.page} / {position.pages}</span>
          <button className={`${styles.edgeControl} ${styles.edgeEnd}`} type="button" onClick={() => move(1)} disabled={loading || (!hasMore && position.page === position.pages)} aria-label={labels.next}><ChevronRightIcon aria-hidden="true" /></button>
        </> : null}
      </div> : <p className={styles.empty}>{labels.empty}</p>}
      <div className={styles.footer}>
        <Link href={group.href} locale={locale} className={styles.viewAll} aria-label={`${labels.viewAll} · ${group.name}`}>{labels.viewAll}<ArrowRightIcon aria-hidden="true" /></Link>
      </div>
    </div>
  </section>;
}

export function HomeProductCarousel({ groups, locale, labels }: { groups: HomeProductGroupView[]; locale: Locale; labels: Labels }) {
  return <>{groups.map((group, index) => <ProductShelf key={group.key} group={group} locale={locale} labels={labels} surface={index % 2 ? "muted" : "plain"} />)}</>;
}
