import { createAttributeDefinition, createBrand, updateBrandRights } from "@/app/admin/actions";
import { LocaleSection } from "@/components/admin/locale-section";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Field, FieldDescription, FieldGroup, FieldLabel, FieldLegend, FieldSet } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectGroup, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { requireSecureAdmin } from "@/lib/admin-session";
import { managedLocaleLabel, managedLocales } from "@/lib/admin-locales";
import { db } from "@/lib/db";

export const metadata = { title: "品牌、分类与参数", robots: { index: false, follow: false } };

export default async function Page({ searchParams }: { searchParams: Promise<{ created?: string; updated?: string; error?: string }> }) {
  await requireSecureAdmin("ADMIN");
  const [query, brands, categories] = await Promise.all([
    searchParams,
    db.brand.findMany({ include: { _count: { select: { products: true } } }, orderBy: { name: "asc" } }),
    db.category.findMany({ include: { translations: { where: { locale: "zh" } }, attributes: { orderBy: { sortOrder: "asc" } } }, orderBy: [{ level: "asc" }, { sortOrder: "asc" }] }),
  ]);
  const activeCategories = categories.filter((item) => item.status !== "ARCHIVED");

  return <main className="flex flex-col gap-8 p-5 md:p-8">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-semibold">品牌、分类与参数</h1><p className="mt-2 text-sm text-muted-foreground">统一维护目录事实和七语显示名称；分类层级最多三级。</p></div><Button render={<a href="/admin/categories/new" />}>新建七语分类</Button></div>
    {query.created || query.updated ? <Alert><AlertTitle>已保存</AlertTitle><AlertDescription>目录变更已写入审计记录。</AlertDescription></Alert> : null}
    {query.error ? <Alert variant="destructive"><AlertTitle>无法保存</AlertTitle><AlertDescription>{query.error}</AlertDescription></Alert> : null}
    <section className="grid items-start gap-6 xl:grid-cols-[minmax(280px,.75fr)_minmax(0,1.25fr)]">
      <Card><CardHeader><CardTitle>新建品牌</CardTitle><CardDescription>Slug、官网和规范名称是全球统一事实；显示名称可按七种语言维护。</CardDescription></CardHeader><CardContent><form action={createBrand}><FieldGroup><Field><FieldLabel htmlFor="brand-name">规范名称（中文默认）</FieldLabel><Input id="brand-name" name="name" required /></Field><Field><FieldLabel htmlFor="brand-slug">Slug</FieldLabel><Input id="brand-slug" name="slug" pattern="[a-z0-9][a-z0-9-]*" required /></Field><Field><FieldLabel htmlFor="brand-website">官方网站</FieldLabel><Input id="brand-website" name="website" type="url" /></Field><div><p className="mb-3 text-sm font-medium">七语显示名称</p><div className="grid gap-3">{managedLocales.map((locale) => <LocaleSection key={locale} locale={locale} complete={false}><Field><FieldLabel htmlFor={`${locale}Name`}>{managedLocaleLabel(locale)}</FieldLabel><Input id={`${locale}Name`} name={`${locale}Name`} required /></Field></LocaleSection>)}</div></div><Field orientation="horizontal"><Checkbox id="rightsConfirmed" name="rightsConfirmed" /><div><FieldLabel htmlFor="rightsConfirmed">已确认经销或展示权</FieldLabel><FieldDescription>此项不替代单张图片的授权确认。</FieldDescription></div></Field><Button type="submit" className="self-start">创建品牌</Button></FieldGroup></form></CardContent></Card>
      <Card><CardHeader><CardTitle>新建参数定义</CardTitle><CardDescription>参数键和单位只维护一次，前台显示标签支持七种语言。</CardDescription></CardHeader><CardContent><form action={createAttributeDefinition}><FieldGroup><div className="grid gap-5 sm:grid-cols-2"><Field><FieldLabel htmlFor="attribute-category">分类</FieldLabel><Select name="categoryId" defaultValue={activeCategories[0]?.id} required><SelectTrigger id="attribute-category" className="w-full"><SelectValue placeholder="选择分类" /></SelectTrigger><SelectContent><SelectGroup>{activeCategories.map((item) => <SelectItem key={item.id} value={item.id}>{item.translations[0]?.name ?? item.key}</SelectItem>)}</SelectGroup></SelectContent></Select></Field><Field><FieldLabel htmlFor="attribute-key">参数键</FieldLabel><Input id="attribute-key" name="key" pattern="[a-z0-9][a-z0-9_.-]*" required /></Field><Field><FieldLabel htmlFor="attribute-type">类型</FieldLabel><Select name="type" defaultValue="TEXT" required><SelectTrigger id="attribute-type" className="w-full"><SelectValue /></SelectTrigger><SelectContent><SelectGroup><SelectItem value="TEXT">文本</SelectItem><SelectItem value="NUMBER">数字</SelectItem><SelectItem value="BOOLEAN">布尔</SelectItem><SelectItem value="SELECT">枚举</SelectItem></SelectGroup></SelectContent></Select></Field><Field><FieldLabel htmlFor="attribute-unit">标准单位</FieldLabel><Input id="attribute-unit" name="standardUnit" /></Field></div><div><p className="mb-3 text-sm font-medium">七语参数标签</p><div className="grid gap-3">{managedLocales.map((locale) => <LocaleSection key={locale} locale={locale} complete={false}><Field><FieldLabel htmlFor={`${locale}Label`}>显示标签</FieldLabel><Input id={`${locale}Label`} name={`${locale}Label`} required /></Field></LocaleSection>)}</div></div><Field><FieldLabel htmlFor="attribute-options">枚举选项</FieldLabel><Textarea id="attribute-options" name="options" placeholder="SELECT 类型时每行一项" /></Field><FieldSet><FieldLegend>用途</FieldLegend><div className="flex flex-wrap gap-5"><Field orientation="horizontal"><Checkbox id="required" name="required" /><FieldLabel htmlFor="required">发布必填</FieldLabel></Field><Field orientation="horizontal"><Checkbox id="filterable" name="filterable" /><FieldLabel htmlFor="filterable">用于筛选</FieldLabel></Field><Field orientation="horizontal"><Checkbox id="comparable" name="comparable" defaultChecked /><FieldLabel htmlFor="comparable">用于对比</FieldLabel></Field></div></FieldSet><Button type="submit" className="self-start" disabled={!activeCategories.length}>创建参数定义</Button></FieldGroup></form></CardContent></Card>
    </section>
    <Card><CardHeader><CardTitle>当前目录</CardTitle><CardDescription>{brands.length} 个品牌，{categories.length} 个分类。品牌显示名称、分类名称/说明/SEO 和参数标签均支持七种语言。</CardDescription></CardHeader><CardContent><div className="grid gap-8 lg:grid-cols-2"><section><h2 className="mb-3 text-sm font-semibold">品牌</h2><div className="divide-y border-y">{brands.map((brand) => <div className="flex items-center gap-3 py-3" key={brand.id}><form action={updateBrandRights} className="min-w-0 flex-1"><input type="hidden" name="brandId" value={brand.id} /><Field orientation="horizontal"><Checkbox id={`brand-rights-${brand.id}`} name="rightsConfirmed" defaultChecked={brand.rightsConfirmed} /><div className="min-w-0 flex-1"><FieldLabel htmlFor={`brand-rights-${brand.id}`}>{brand.name}</FieldLabel><p className="mt-1 text-xs text-muted-foreground">{brand._count.products} 个产品{brand.archivedAt ? " · 已归档" : ""}</p></div><Button type="submit" size="xs" variant="outline">保存</Button></Field></form><Button render={<a href={`/admin/taxonomy/brand/${brand.id}`} />} size="xs" variant="ghost">编辑七语</Button></div>)}</div></section><section><div className="mb-3 flex items-center justify-between"><h2 className="text-sm font-semibold">分类与参数</h2><Button render={<a href="/admin/categories" />} size="xs" variant="outline">管理分类</Button></div><div className="divide-y border-y">{categories.map((category) => <div className="py-4" key={category.id}><div className="flex items-center justify-between gap-3"><strong className="text-sm">{category.translations[0]?.name ?? category.key}</strong><div className="flex gap-2"><Badge variant="outline">L{category.level}</Badge><Badge variant="secondary">{category.status}</Badge></div></div><p className="mt-1 text-xs text-muted-foreground">{category.key} · {category.attributes.length} 个参数</p><div className="mt-3 flex flex-wrap gap-2"><Button render={<a href={`/admin/categories/${category.id}`} />} size="xs" variant="outline">编辑七语分类</Button>{category.attributes.map((attribute) => <Button key={attribute.id} render={<a href={`/admin/taxonomy/attribute/${attribute.id}`} />} size="xs" variant="ghost">{(attribute.labels as Record<string, string>).zh ?? attribute.key}</Button>)}</div></div>)}</div></section></div></CardContent></Card>
  </main>;
}
