import { createManualProduct } from "@/app/admin/actions";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Field, FieldGroup, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectGroup, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { db } from "@/lib/db";
export const metadata = { title: "新建产品", robots: { index: false, follow: false } };
export default async function Page({ searchParams }: { searchParams: Promise<{ error?: string }> }) { const [query, brands, categories] = await Promise.all([searchParams, db.brand.findMany({ where: { archivedAt: null }, orderBy: { name: "asc" } }), db.category.findMany({ where: { status: { not: "ARCHIVED" } }, include: { translations: { where: { locale: "zh" } } }, orderBy: { sortOrder: "asc" } })]); return <main className="flex flex-col gap-6 p-5 md:p-8"><div><h1 className="text-2xl font-semibold">新建产品</h1><p className="mt-2 text-sm text-muted-foreground">先录入三语最小完整资料，保存为草稿后继续补充参数和素材。</p></div>{query.error === "inactive-taxonomy" ? <Alert variant="destructive"><AlertTitle>无法创建产品</AlertTitle><AlertDescription>所选品牌或分类已停用，请刷新页面后重新选择。</AlertDescription></Alert> : null}<form action={createManualProduct} className="max-w-4xl rounded-lg border bg-card p-6"><FieldGroup><div className="grid gap-5 sm:grid-cols-2"><Field><FieldLabel htmlFor="model">型号</FieldLabel><Input id="model" name="model" required /></Field><Field><FieldLabel htmlFor="sku">SKU（选填）</FieldLabel><Input id="sku" name="sku" /></Field><Field><FieldLabel htmlFor="brandId">品牌</FieldLabel><Select name="brandId" defaultValue={brands[0]?.id} required><SelectTrigger id="brandId" className="w-full"><SelectValue placeholder="选择品牌" /></SelectTrigger><SelectContent><SelectGroup>{brands.map((brand) => <SelectItem key={brand.id} value={brand.id}>{brand.name}</SelectItem>)}</SelectGroup></SelectContent></Select></Field><Field><FieldLabel htmlFor="categoryId">分类</FieldLabel><Select name="categoryId" defaultValue={categories[0]?.id} required><SelectTrigger id="categoryId" className="w-full"><SelectValue placeholder="选择分类" /></SelectTrigger><SelectContent><SelectGroup>{categories.map((category) => <SelectItem key={category.id} value={category.id}>{category.translations[0]?.name ?? category.key}</SelectItem>)}</SelectGroup></SelectContent></Select></Field></div>{(["zh", "en", "ru"] as const).map((locale) => <div className="grid gap-4 border-t pt-5" key={locale}><h2 className="font-semibold">{locale.toUpperCase()}</h2><Field><FieldLabel htmlFor={`${locale}Name`}>产品名称</FieldLabel><Input id={`${locale}Name`} name={`${locale}Name`} required /></Field><Field><FieldLabel htmlFor={`${locale}Definition`}>40–60 字直接定义</FieldLabel><Textarea id={`${locale}Definition`} name={`${locale}Definition`} required minLength={40} /></Field></div>)}<Button type="submit" className="self-start" disabled={!brands.length || !categories.length}>创建草稿</Button></FieldGroup></form></main>; }
