import { PlusIcon } from "lucide-react";
import { changeProductStatus } from "@/app/admin/actions";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { db } from "@/lib/db";
export const metadata = { title: "产品管理", robots: { index: false, follow: false } };
export default async function Page({ searchParams }: { searchParams: Promise<{ error?: string; success?: string }> }) { const query = await searchParams; const products = await db.product.findMany({ include: { brand: true, category: true, translations: { where: { locale: "zh" } } }, orderBy: { updatedAt: "desc" } }); return <main className="flex flex-col gap-6 p-5 md:p-8"><div className="flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-2xl font-semibold">产品与内容</h1><p className="mt-2 text-sm text-muted-foreground">结构化产品字段、三语内容与发布门禁。</p></div><Button render={<a href="/admin/products/new" />}><PlusIcon data-icon="inline-start" />新建产品</Button></div>{query.error ? <Alert variant="destructive"><AlertTitle>无法发布</AlertTitle><AlertDescription>{query.error}</AlertDescription></Alert> : null}{query.success ? <Alert><AlertTitle>状态已更新</AlertTitle><AlertDescription>相关页面缓存已刷新。</AlertDescription></Alert> : null}<div className="rounded-lg border bg-card"><Table><TableHeader><TableRow><TableHead>型号 / 产品</TableHead><TableHead>品牌</TableHead><TableHead>状态</TableHead><TableHead>更新时间</TableHead><TableHead>操作</TableHead></TableRow></TableHeader><TableBody>{products.map((product) => <TableRow key={product.id}><TableCell><a className="font-medium hover:underline" href={`/admin/products/${product.id}`}>{product.model}<span className="mt-1 block text-xs font-normal text-muted-foreground">{product.translations[0]?.name ?? "缺少中文内容"}</span></a></TableCell><TableCell>{product.brand.name}</TableCell><TableCell><Badge variant={product.status === "PUBLISHED" ? "default" : product.status === "NEEDS_REVIEW" ? "destructive" : "secondary"}>{product.status}</Badge></TableCell><TableCell>{product.updatedAt.toISOString().slice(0, 10)}</TableCell><TableCell><div className="flex gap-1"><Button variant="ghost" size="sm" render={<a href={`/admin/products/${product.id}`} />}>编辑</Button>{product.status !== "PUBLISHED" ? <form action={changeProductStatus}><input type="hidden" name="productId" value={product.id} /><input type="hidden" name="status" value="PUBLISHED" /><Button variant="ghost" size="sm" type="submit">发布</Button></form> : <form action={changeProductStatus}><input type="hidden" name="productId" value={product.id} /><input type="hidden" name="status" value="ARCHIVED" /><Button variant="ghost" size="sm" type="submit">归档</Button></form>}</div></TableCell></TableRow>)}</TableBody></Table></div></main>; }
